trigger:
  - main

pool:
  name: 'Default'  # Or whatever pool your agent is in

steps:
  - checkout: self
    clean: true

  - script: |
      echo "Checking Azure login..."
      az account show
      echo "Creating resource group..."
      az group create --name DevOpsRG --location eastus
    displayName: 'Deploy Resource Group'
